- name: UFW Set N Check 
  hosts: your_hosts_group
  become: yes
  vars_files:
  - your_vars_file.yml
  vars:
    ansible_become_pass: "{{ hosts_become_pass }}"
    dest_filepath: "{{ ufw_sh_file }}"
  tasks:
    - name: Install UFW firewall
      apt: name=ufw update_cache=yes state=latest
      
    - name: Check directory exists
      file:
        path: "{{ dest_filepath | dirname }}"
        recurse: true
        state: directory

    - name: Copy UFW script to remote instance
      template: 
        src: "{{ src_path }}/ufw_set_n_check.sh"
        dest: "{{ dest_filepath }}"
        mode: 0755
        
    - name: Run UFW script to remote instance
      ansible.builtin.script: "{{ src_path }}/ufw_set_n_check.sh"
      
    - name: Enable UFW
      community.general.ufw:
        state: enabled