---
- name: Install and configure Bind9 DNS server on Debian
  hosts: dns_servers
  become: true
  vars:
    domain_name: "example.com"
    dns_listen_address: "{{ ansible_default_ipv4.address }}"
    dns_forwarders:
      - "1.1.1.1"
      - "9.9.9.9"
    dns_records:
      - name: "www.webserver.example.com."
        type: "A"
        value: "192.168.1.10"
      - name: "mail"
        type: "A"
        value: "192.168.1.20"
      - name: "example.com."
        type: "MX"
        value: "10 mail.example.com."

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Bind9 packages
      apt:
        name:
          - bind9
          - bind9utils
          - dnsutils
        state: present

    - name: Create configuration directory if it doesn't exist
      file:
        path: /etc/bind/zones
        state: directory
        owner: root
        group: bind
        mode: '0775'

    - name: Configure named.conf.options
      template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
        owner: root
        group: bind
        mode: '0644'
      notify: Restart Bind9

    - name: Configure named.conf.local
      template:
        src: templates/named.conf.local.j2
        dest: /etc/bind/named.conf.local
        owner: root
        group: bind
        mode: '0644'
      notify: Restart Bind9

    - name: Create forward zone file
      template:
        src: templates/db.forward.j2
        dest: /etc/bind/zones/db.{{ domain_name }}
        owner: root
        group: bind
        mode: '0644'
      notify: Restart Bind9

    - name: Create reverse zone file
      template:
        src: templates/db.reverse.j2
        dest: /etc/bind/zones/db.192.168.1
        owner: root
        group: bind
        mode: '0644'
      notify: Restart Bind9

    - name: Enable and start Bind9 service
      systemd:
        name: bind9
        state: started
        enabled: yes

    - name: Allow DNS in UFW firewall if enabled
      ufw:
        rule: allow
        port: 53
        proto: any
      failed_when: false

  handlers:
    - name: Restart Bind9
      systemd:
        name: bind9
        state: restarted