- name: UFW Set N Check All
  hosts: your_hosts_group
  become: true
  vars_files:
    - your_vars_file.yml
  vars:
    ansible_become_pass: "{{ your_hosts_group_become_pass }}"
    dest_filepath: "{{ scripts_path }}"
  tasks:
    - name: Install UFW firewall
      apt: name=ufw update_cache=yes state=latest
    - name: Check directory exists
      file:
        path: "{{ scripts_path }}"
        recurse: true
        state: directory
    - name: Copy UFW script to remote instance
      copy:
        src: "{{ all_src_path }}/scripts/ufw_set_n_check.sh"
        dest: "{{ dest_filepath }}/ufw_set_n_check.sh"
        mode: 0755
    - name: Run UFW script to remote instance
      ansible.builtin.script: "{{ all_src_path }}/scripts/ufw_set_n_check.sh"
    - name: Enable UFW
      community.general.ufw:
        state: enabled